import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../domain/music_models.dart';

/// The record, as a document somebody can send.
///
/// This is the point of the whole feature. A history you can only read inside
/// the app helps nobody in an argument — what ends an argument is a dated
/// document you can attach to a message, print, or hand to a solicitor.
///
/// Deliberately plain. No colour, no logo across the top, no design. A page
/// that looks marketed reads as marketing; a page that looks like a record
/// reads as a record, and the second one is the only one worth printing.
abstract final class ProvenanceExport {
  static Future<void> print({
    required String songTitle,
    required List<ProvenanceEvent> events,
  }) {
    return Printing.layoutPdf(
      name: '${_fileName(songTitle)}-history.pdf',
      onLayout: (format) => _document(songTitle, events).save(),
    );
  }

  static pw.Document _document(String songTitle, List<ProvenanceEvent> events) {
    final document = pw.Document();
    final generated = DateTime.now();

    document.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(44),
        // Repeated on every page, because a printed record is read out of
        // order and a page three that does not say which song it belongs to
        // is a page three nobody can rely on.
        header: (context) => context.pageNumber == 1
            ? pw.SizedBox()
            : pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 12),
                child: pw.Text(
                  '$songTitle — history (page ${context.pageNumber})',
                  style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
                ),
              ),
        footer: (context) => pw.Padding(
          padding: const pw.EdgeInsets.only(top: 10),
          child: pw.Text(
            'Generated by CoLabRoom ${_stamp(generated)} · '
            'page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(fontSize: 7.5, color: PdfColors.grey600),
          ),
        ),
        build: (_) => <pw.Widget>[
          pw.Text(
            songTitle,
            style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 3),
          pw.Text(
            'History of contributions',
            style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey800),
          ),
          pw.SizedBox(height: 14),

          // The caveat sits above the evidence, not below it. Somebody who
          // reads the table first and the limits afterwards has already formed
          // a view, and a record that lets a person over-rely on it has done
          // them harm rather than good.
          pw.Container(
            padding: const pw.EdgeInsets.all(9),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey400, width: .5),
            ),
            child: pw.Text(
              'This is a record of activity, not a registration of ownership. '
              'It shows what happened inside CoLabRoom and when, as recorded '
              'at the time by the server rather than by any participant. It '
              'does not establish who owns a work, and it is not legal advice.',
              style: const pw.TextStyle(fontSize: 8.5, lineSpacing: 1.6, color: PdfColors.grey900),
            ),
          ),
          pw.SizedBox(height: 16),

          pw.Table(
            border: pw.TableBorder(
              horizontalInside: pw.BorderSide(color: PdfColors.grey300, width: .5),
              bottom: pw.BorderSide(color: PdfColors.grey300, width: .5),
              top: pw.BorderSide(color: PdfColors.grey600, width: .8),
            ),
            columnWidths: const <int, pw.TableColumnWidth>{
              0: pw.FixedColumnWidth(96),
              1: pw.FixedColumnWidth(78),
              2: pw.FixedColumnWidth(84),
              3: pw.FlexColumnWidth(),
            },
            children: <pw.TableRow>[
              pw.TableRow(
                children: <pw.Widget>[
                  _head('When (local)'),
                  _head('Who'),
                  _head('What'),
                  _head('Detail'),
                ],
              ),
              for (final event in events)
                pw.TableRow(
                  children: <pw.Widget>[
                    _cell(_stamp(event.at)),
                    _cell(event.whoName),
                    _cell(event.event),
                    _cell(event.detail),
                  ],
                ),
            ],
          ),

          pw.SizedBox(height: 14),
          pw.Text(
            '${events.length} recorded events. '
            'Where a line reads "sha256", that is a fingerprint of the audio '
            'file as uploaded: two recordings with the same value are the '
            'same recording.',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700, lineSpacing: 1.5),
          ),
        ],
      ),
    );
    return document;
  }

  static pw.Widget _head(String text) => pw.Padding(
        padding: const pw.EdgeInsets.symmetric(vertical: 5, horizontal: 3),
        child: pw.Text(
          text,
          style: pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold),
        ),
      );

  static pw.Widget _cell(String text) => pw.Padding(
        padding: const pw.EdgeInsets.symmetric(vertical: 4, horizontal: 3),
        child: pw.Text(
          text,
          style: const pw.TextStyle(fontSize: 8.5, lineSpacing: 1.3),
        ),
      );

  /// Sortable and unambiguous, rather than pretty. A record read in another
  /// country should not have to guess whether 06/09 is September or June.
  static String _stamp(DateTime at) {
    String two(int v) => v.toString().padLeft(2, '0');
    return '${at.year}-${two(at.month)}-${two(at.day)} '
        '${two(at.hour)}:${two(at.minute)}';
  }

  static String _fileName(String title) {
    final cleaned = title
        .replaceAll(RegExp(r'[^A-Za-z0-9 _-]'), '')
        .replaceAll(RegExp(r'\s+'), '-')
        .trim();
    return cleaned.isEmpty ? 'song' : cleaned.toLowerCase();
  }
}
