-- Remember that a band has been warned, so they are warned once.
--
-- Layers expire at 90 days untouched. That number is defensible only because
-- three things are true together: it counts from when somebody last *played*
-- the layer rather than when it was recorded, so a song anyone still opens
-- never expires; a copy can be taken at any point from the export button; and
-- nobody loses anything without being told first.
--
-- This column is the third one. The sweep warns at 75 days and deletes at 90,
-- and without somewhere to record the warning it would arrive every day for a
-- fortnight — which is not a warning, it is a reason to turn notifications
-- off, and then the real one is never seen.
--
-- Worth being explicit about why this is not the same policy as stems, which
-- also expire at 90 days. A stem is derived: it can be recomputed from a
-- recording that never expires, so losing one costs GPU time. A layer is
-- somebody's actual playing and cannot be regenerated by anything. The two
-- windows matching is a coincidence of what turned out reasonable, not a
-- shared rule, and if one moves the other should not follow automatically.

alter table public.song_layers
  add column if not exists expiry_warned_at timestamptz;

-- The sweep's read: layers not touched lately, not yet warned. Partial,
-- because the answer is almost always an empty set on a healthy table and
-- there is no reason to index the rows somebody is still using.
create index if not exists song_layers_expiry_idx
  on public.song_layers (last_opened_at)
  where expiry_warned_at is null;
